CXX=c++
FLAGS=-Wall -std=c++11  

all:
	$(CXX) inline_namespace_ex.cc -o namespace-test $(FLAGS)
	$(CXX) namespace2.cpp -o namespace-test2 $(FLAGS)
	$(CXX) namespace3.cpp -o namespace-test3 $(FLAGS)
clean:
	rm -rf namespace-test namespace-test2 namespace-test3
