CFLAGS= -std=c++11

all:
	$(CXX) $(CFLAGS) scroll.cpp -o textscroll
	$(CXX) $(CFLAGS) textscroll.cpp -o plaintext_scroll
	$(CXX) $(CFLAGS) linescroll.cpp -o linescroll
clean:
	rm -f textscroll plaintext_scroll linescroll
