CXX=c++
FLAGS=-Wall -std=c++11 
all:
	$(CXX)  $(FLAGS)  constexpr.cc -o constexpr-test  
	$(CXX)  $(FLAGS)  constexpr-test.cc -o constexpr-test2
	$(CXX) $(FLAGS) constexpr_example.cpp -o constexpr-test3
clean:
	rm -f constexpr-test constexpr-test2 constexpr-test3
