
CXX_FLAGS=-std=c++11

all: rvalue1-test rvalue2-test rvalue3-test rvalue4-test rvalue5-test

rvalue1-test: rvalue1.cpp
	$(CXX) $(CXX_FLAGS) rvalue1.cpp -o rvalue1-test
rvalue2-test: rvalue2.cpp
	$(CXX) $(CXX_FLAGS) rvalue2.cpp -o rvalue2-test
rvalue3-test: rvalue3.cpp
	$(CXX) $(CXX_FLAGS) rvalue3.cpp -o rvalue3-test
rvalue4-test: rvalue4.cpp
	$(CXX) $(CXX_FLAGS) rvalue4.cpp -o rvalue4-test
rvalue5-test: rvalue5.cpp
	$(CXX) $(CXX_FLAGS) rvalue5.cpp -o rvalue5-test
clean:
	rm -f rvalue1-test rvalue2-test rvalue3-test rvalue4-test rvalue5-test
