CXX=c++
FLAGS= -Wall -std=c++11  

all:
	$(CXX) timetest.cc -o time-test $(FLAGS)
	$(CXX) scoped_t.cc -o scoped-test $(FLAGS)
	$(CXX) looptest.cc -o looptest-test $(FLAGS)
clean:
	rm -f time-test scoped-test looptest-test
