CXX_FLAGS=-std=c++11

all: libdemo.so prog

libdemo.so: lib.cpp
	$(CXX) $(CXX_FLAGS) -fPIC lib.cpp -shared -o libdemo.so

prog: prog.cpp header.h
	$(CXX) $(CXX_FLAGS) prog.cpp -o program -ldl
clean:
	rm -f program libdemo.so
