CXX=c++
FLAGS=-Wall  -std=c++11
all: randtest

randtest: r.cc
	$(CXX) r.cc -o randtest $(FLAGS)
#	$(CXX) shuffle.cc -o randtest2 $(FLAGS)
#	$(CXX) shuffle2.cc -o randtest3 $(FLAGS)
clean:
	rm -f *.o randtest randtest2 randtest3
