CXX_FLAGS=-std=c++11 -Wall

all: popen-test pipe-test sysvmsgq-ls


popen-test: popen.cpp
	$(CXX) $(CXX_FLAGS) popen.cpp -o popen-test

pipe-test: pipe.cpp
	$(CXX) $(CXX_FLAGS) pipe.cpp -o pipe-test

sysvmsgq-ls: sysvmsgq_ls.cpp
	$(CXX) $(CXX_FLAGS) sysvmsgq_ls.cpp -o sysvmsgq-ls

clean:
	rm -f popen-test pipe-test sysvmsgq-ls
