
CXX_FLAGS=-std=c++11   -Wall

all: sort1-test sort2-test

sort1-test: sort1.cpp
	$(CXX) sort1.cpp -o sort1-test $(CXX_FLAGS)
sort2-test: sort2.cpp
	$(CXX) sort2.cpp -o sort2-test $(CXX_FLAGS)
clean:
	rm -f sort1-test sort2-test
