MAIN_SOURCE=main.cpp
STRING_TEST=string-test.cpp

CXXFLAGS= -std=c++11 

all:
	$(CXX) $(CXXFLAGS) $(MAIN_SOURCE) -o stopwatch-test
	$(CXX) $(CXXFLAGS) $(STRING_TEST) -o stopwatch-string
clean:
	rm -f stopwatch-test stopwatch-string
