all:
	make -C environment/
	make -C forktest/
	make -C info/
	make -C io/
	make -C memory/
	make -C pthread/
	make -C setjmp/
	make -C time/
	make -C user/
clean:
	make -C environment/ clean
	make -C forktest/ clean
	make -C info/ clean
	make -C io/ clean
	make -C memory/ clean
	make -C pthread/ clean
	make -C setjmp/ clean
	make -C time/ clean
	make -C user/ clean
