all:
	make -C attr/
	make -C directory/
	make -C environment/
	make -C process/
	make -C pseudo/
	make -C getopt/
	make -C info/
	make -C io/
	make -C ipc/
	make -C login/
	make -C memory/
	make -C network/
	make -C pthread/
	make -C setjmp/
	make -C shared/
	make -C signal/
	make -C syslog/
	make -C time/
	make -C timer/
	make -C user/
clean:
	make -C attr/ clean
	make -C directory/ clean
	make -C environment/ clean
	make -C process/ clean
	make -C pseudo/ clean
	make -C info/ clean
	make -C getopt/ clean
	make -C io/ clean
	make -C ipc/ clean
	make -C login/ clean
	make -C memory/ clean
	make -C network/ clean
	make -C pthread/ clean
	make -C setjmp/ clean
	make -C shared/ clean
	make -C signal/ clean
	make -C syslog/ clean
	make -C time/ clean
	make -C timer/ clean
	make -C user/ clean
