CXX_FLAGS=-std=c++11

all:
	$(CXX) $(CXX_FLAGS) template-function.cpp -o temp-func
	$(CXX) $(CXX_FLAGS) template-class.cpp -o temp-class
	$(CXX) $(CXX_FLAGS) template-class2.cpp -o temp-class2
	$(CXX) $(CXX_FLAGS) template-class3.cpp -o temp-class3
	$(CXX) $(CXX_FLAGS) template-template.cpp -o template-temp
	$(CXX) $(CXX_FLAGS) template-union.cpp -o template-un
	$(CXX) $(CXX_FLAGS) template-type.cpp -o template-type
	$(CXX) $(CXX_FLAGS) template-inst.cpp -o template-inst
	$(CXX) $(CXX_FLAGS) template-spec.cpp -o template-spec
	$(CXX) $(CXX_FLAGS) template-pointer.cpp -o template-ptr
clean:
	rm -f temp-func temp-class temp-class2 temp-class3 template-temp template-un template-type template-inst template-spec template-ptr

