all:
	make -C simple_lib
	make -C simple_lib2
	make -C dynamic_load
	make -C dynamic_init
clean:
	make -C simple_lib clean
	make -C simple_lib2 clean
	make -C dynamic_load clean
	make -C dynamic_init clean
