
FLAGS=-Wall -std=c++11 

all: temp1-test temp2-test

temp1-test: temp1.cc
	$(CXX) temp1.cc -o temp1-test $(FLAGS)
temp2-test: temp2.cc
	$(CXX) temp2.cc -o temp2-test $(FLAGS)
clean:	
	rm -f temp1-test temp2-test
