CXX=c++
CXXFLAGS=-Wall -std=c++11  

all:
	$(CXX) it.cpp -o it-test $(CXXFLAGS)
	$(CXX) it2.cpp -o it-test2 $(CXXFLAGS)
	$(CXX) it3.cpp -o it-test3 $(CXXFLAGS)
clean:
	rm -f it-test it-test2 it-test3
