CXX=c++
FLAGS= -O2 -Wall -std=c++11  

all:
	$(CXX) move_test.cc -o movet $(FLAGS)
	$(CXX) move_test2.cc -o move-test2 $(FLAGS)
	$(CXX) move_test3.cc -o move-test3 $(FLAGS)
clean:
	rm -f movet move-test2 move-test3
