CXX_FLAGS=-std=c++11

all: libdemo.so prog

libdemo.so: lib.cpp
	$(CXX) $(CXX_FLAGS) -fPIC lib.cpp -shared -Wl,-soname,libdemo.so.1 -o libdemo.so.1.0.0
	ln -sf libdemo.so.1.0.0 libdemo.so.1
	ln -sf libdemo.so.1 libdemo.so

prog: prog.cpp header.h
	$(CXX) $(CXX_FLAGS) prog.cpp -o program -L. -ldemo
clean:
	rm -f program libdemo.so libdemo.so.1.0.0 libdemo.so.1 libdemo.so
